# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(594, 612)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(130, 20, 351, 531))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(16)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 50, 251, 431))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ShowImage = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ShowImage.setObjectName("ShowImage")
        self.verticalLayout.addWidget(self.ShowImage)
        self.ShowPara = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ShowPara.setObjectName("ShowPara")
        self.verticalLayout.addWidget(self.ShowPara)
        self.ShowModel = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ShowModel.setObjectName("ShowModel")
        self.verticalLayout.addWidget(self.ShowModel)
        self.ShowAcc = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ShowAcc.setObjectName("ShowAcc")
        self.verticalLayout.addWidget(self.ShowAcc)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.Test = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Test.setObjectName("Test")
        self.verticalLayout.addWidget(self.Test)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 594, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "VGG16"))
        self.ShowImage.setText(_translate("MainWindow", "1. Show Train images"))
        self.ShowPara.setText(_translate("MainWindow", "2. Show HyperParameters"))
        self.ShowModel.setText(_translate("MainWindow", "3. Show Model Shorcut"))
        self.ShowAcc.setText(_translate("MainWindow", "4. Show Accuracy"))
        self.Test.setText(_translate("MainWindow", "5. Test"))
